### ISSUE TITLE
Not receiving Snapshot Offers

### ISSUE THREAD

**Issue by jlturner** [Horusiath/Akkling#119]
It looks like SnapshotOffer(s) are being swallowed up in the `FunPersistentActor<'Message>`'s Next method. I'm trying to figure out how I can get these snapshots when my cluster shards are recovering.  When inspecting `message` in this method, I can see the `SnapshotOffer`, but I believe it's falling into the `| other ->` branch of the match.

Let me know what your thoughts on how to retrieve the `SnapshotOffer` might be. Thanks for your work on your great Akka.Net wrapper!

https://github.com/Horusiath/Akkling/blob/908edccbb2d21ef8087731608037d8de0d82f41f/src/Akkling.Persistence/PersistentActor.fs#L184

**Comment by jlturner** [comment]
So it looks like if I unify the type `'Message` with `obj` it'll just forward everything from `FunPersistentActor` and I can match this way:
```fsharp
actor {
  let! (msg: obj) = mailbox.Receive()
  match msg with
  | :? SnapshotOffer ->
    let snapshotOffer: SnapshotOffer = unbox msg
    ... use snapshot
  | :? MyMessage ->
    match unbox msg
    | Message v -> ... handle message
}
```

But I'm still looking for a better way. I'd rather not have my actor be of type `obj`, although I suppose I could wrap an interface around all this with some other type that get's `box` 'd to `obj`.

**Comment by Horusiath** [comment]
Unfortunately with the current design it's not possible to have both Akka-specific messages and user defined messages within the same type-safe contract. It's mostly due to lack of union types in F# (don't mistake them for discriminated unions).

My general approach for the incoming future is to port [akka-typed](https://doc.akka.io/docs/akka/current/typed/persistence.html) - probably using C# - and turn Akkling into thing F# wrapper around that.

**Comment by jlturner** [comment]
Thanks, I played around with the source for a few evenings and arrived at the same conclusion. The snapshot type would have to be passed around everywhere and wouldn't make sense for lots of Akka cases anyway.

**Comment by Horusiath** [comment]
@jlturner  In case if you need, there's a function called `retype`, which is a workaround for the problem at the moment: it allows you to change any `IActorRef<'t>` into `IActorRef<'u>` - the most common use case is to narrow generic type from `obj` to user type message.
