### ISSUE TITLE
Dependency Injection when creating actors

### ISSUE THREAD

**Issue by Swoorup** [Horusiath/Akkling#124]
Is it possible to use DI when spawning actors, currently passing it as functions, but would be nice to use some sort of existing DI solutions such as autofac, or .net core built in solution.

**Comment by Horusiath** [comment]
There's no out-of-the-box support for IoC containers (other than what Akka DI already provides). Dependency Injection as understood by existing .NET IoC container libraries doesn't quite work with functional approach:

- I naturally binds your services to Object Oriented Programming model (interfaces and classes), which doesn't quite work with functional approach (generics and functions).
- I doesn't understand concept of partial function application (as it's not representable in .NET reflection API).
- I doesn't offer incremental component creation: you either must construct entire object graph up-front in the root component or pass a "factory" object that will be used instead.
- It doesn't really know how to deal with abstractions: you must have 1-1 binding between source and target type (usually interface and implementing class). If you have one source type eg. `unit -> TimeSpan` and 5 different implementations of it, used in different places depending on the context, then configuration of DI container changes your system into a minefield fused at runtime.
