### ISSUE TITLE
How actors know their entity ID ?

### ISSUE THREAD

**Issue by codingedgar** [Horusiath/Akkling#126]
The doc states: 

> In some cases, the actor may need to know the entityId associated with it. This can be achieved using the entityPropsFactory parameter to ClusterSharding.Start or ClusterSharding.StartAsync. The entity ID will be passed to the factory as a parameter, which can then be used in the creation of the actor.

However the `entityFactoryFor` doesn't let us add `entityPropsFactory` or does it?

I'm new to akkling, maybe there's a way to do this or maybe it is unnecessary, idk how to let know the auto spawned actor know what's they `entityId`

**Comment by codingedgar** [comment]
I guess `ctx.Self.Path.Name` can be the `entityId`?

**Comment by Horusiath** [comment]
Hi @codingedgar . Yes, in the case of Akkling the approach is that entity id is accessible as current actor's name. By the same virtue, its shardId is its parent's name (`ctx.Self.Path.Parent.Name`). The general format is: `akka.tcp://{system-name}@{host}:{ip}/user/{shard-type}/{shard-id}/{entity-id}`

**Comment by codingedgar** [comment]
Thanks, i'll use that from now on.

(I see shards are part of `system` tho, so they go under `system/sharding/` instead of `/user`, not sure if for some other reason they are also in `/user/`?).
