### ISSUE TITLE
spawnSingleton unhandled event

### ISSUE THREAD

**Issue by ingted** [Horusiath/Akkling#127]
Hi,

If I spawn a singleton like this,

```
    let pingpong i =
        let rec pingpong0 msg =
            printfn "pingpong %d: %s" i msg
            become pingpong0
        pingpong0
    let singleme_a1 = 
        spawnSingleton PoisonPill.Instance system1 "sme_a" (
            props(actorOf (pingpong 1))
        )
    singleme_a1 <! "ooo1"
```

I found it warns

```
[WARNING][9/2/2020 2:39:37 AM][Thread 0005][akka.tcp://cluster-system@localhost:5000/user/sme_a] unhandled event ooo1 in state Oldest
```

Is there anything wrong in my code?

**Comment by Horusiath** [comment]
Hi @ingted . Is this entire code? Are you sure your program doesn't stop right after sending a message: singleton creation and `<!` are non-blocking operations, so if that's your last statement in the program, it will terminate before establishing a singleton or processing the message.

**Comment by ingted** [comment]
Hi @Horusiath ,

Thank's for your kind reply! 
It is a snippet...
And after investigation, I fould that singleton doesn't support directly contact.
[It's normal behavior.](https://github.com/akkadotnet/akka.net/issues/3427)


Regards
Anibal
