### ISSUE TITLE
How to use persistence views/query

### ISSUE THREAD

**Issue by Swoorup** [Horusiath/Akkling#129]
It seems that `propsView` doesn't exist as mentioned in the wiki or examples? Was wondering if I have to fall back on using plain C# api instead?

**Comment by Horusiath** [comment]
Persistent views are part of obsolete API AFAIK. The recommended path is to use persistent streams and build projections directly from them.

**Comment by Swoorup** [comment]
Do you mean this right? https://getakka.net/articles/persistence/persistence-query.html
Nevertheless, I used the C# api to build the `Source<_,_` type. Thank you.
