### ISSUE TITLE
Unable to find "propsView" 

### ISSUE THREAD

**Issue by ingted** [Horusiath/Akkling#134]
Hi,

In example "https://github.com/Horusiath/Akkling/blob/master/examples/persistence-streams.fsx"

There is a function called propsView, where can I find the definition of it?

**Comment by Horusiath** [comment]
If I remember correctly persistent views are have been removed from Akka.NET API somewhere around v1.4. They have been replaced directly by using [ReadJournals](https://getakka.net/articles/persistence/persistence-query.html) and Akka Streams API.

**Comment by ingted** [comment]
Hi Horusiath, 
Thank you so much!!
