### ISSUE TITLE
Is there an eaiser way to retain non-persistent message details for persistent actor?

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#142]
I am implementing PersistnceSupervisor for a persistent actor as described here:
https://devops.petabridge.com/articles/state-management/akkadotnet-persistence-failure-handling.html

The implementation is rather straighforward in C# but F# gives a challenge. In C# API there is away to send a lambda that will be executed once the event is persisted, like here:

```
            Command<AddToCount>(e =>
            {
                Persist(e.CountValue, n =>
                {
                    // Skipped: update actor state

                    // ACK the message back to parent
                    Context.Parent.Tell(new Confirmation(e.ConfirmationId, PersistenceId));
                });
            });

```
The example above shows how the parent it acknowledged using ConfirmationId that was sent with the message _but not persisted_.

Now enter F#.  Let's take the persistence example (https://github.com/Horusiath/Akkling/blob/master/examples/persistence.fsx). In order to write event to event journal the code needs to sent Persist message, the underlying payload will be persisted and the actor will receive back Event. So there is no way to attach any context to the message being persisted that won't be lost after the message is persisted and sent back to the actor as an Event.

Let's try to slightly modify scenario in the sample code persistence.fsx. The sender does not only increment/decrement counter but with expects that each inc/dec message sends back a response with the current counter value and the original command, some kind of receipt. How can we achieve this? In C# it will be straightforward - the original command will be available in the lambda that is passed to Persist handler. With F# it becomes quite tricky, so I had to do this:

```
let counter =
    spawn system "counter-1" <| propsPersist(fun mailbox ->
        let rec loop state =
            actor {
                let! msg = mailbox.Receive()
                match msg with
                | Event(changed) -> return! loop (state + changed.Delta)
                | Command(cmd) ->
                    match cmd with
                    | GetState ->
                        mailbox.Sender() <! state
                        return! loop state
                    | Inc -> 
                        mailbox.Stash()
                        return persisting state (mailbox.Sender()) cmd
                    | Dec -> 
                        mailbox.Stash()
                        return persisting state (mailbox.Sender()) cmd
            }
        and persisting state sender cmd =
            mailbox.UnstashAll()
            actor {
                let! msg = mailbox.Receive()
                match msg with
                | Event(changed) -> 
                    let state = state + changed.Delta
                    sender <! (cmd, state)
                    return! loop state
                | Command(cmd) ->
                    match cmd with
                    | Inc -> return Persist (Event { Delta = 1 })
                    | Dec -> return Persist (Event { Delta = -1 })
                    | _ -> unhandled()
            }
        loop 0)

```

Does it need to be so complicated? I wish I didn't but how else will I be able to pass the original cmd so it will be available _after_ the event is persisted and sent back to the actor?

**Comment by object** [comment]
I guess I can vastly simplify what I am trying to achive. Given the C# example:

```
public class MyPersistentActor : UntypedPersistentActor
{
    protected override void OnCommand(object message)
    {
        if (message is string text)
        {
            Persist($"{text[0]}", e => Sender.Tell($"{text}"));
        }
    }
}

```
The example above only persists the first character of the string (text) that it receives as a command. Upon succesfully persisting this character it invokes a callback that sends the original text to the sender. How this can be achieved using F# implementation that doesn't expose a way of providing a callback?

**Comment by object** [comment]
I saw you just merged your own PR with andThen extension. It looks like it should solve my challenge. Any plan to release Akkling 0.11?

**Comment by Horusiath** [comment]
Yes, I'll try to do that this weekend or just right after. Still need to be sure that the `andThen` parameter function signature is good.

**Comment by object** [comment]
Yeah I was also thinking about the name. But didn't come up with any better.

**Comment by object** [comment]
What about Effects.continueWith? ContinueWith is well known in .NET world and is used to chain tasks, so it fits quite well semantically.

**Comment by JacksonCribb** [comment]
Akka JVM uses [`thenRun`](https://doc.akka.io/docs/akka/current/typed/persistence.html#effects-and-side-effects) but it has a signature of `'state -> unit` so it wouldn't be an identical concept. Either name seems fine. 

Mimicking C#'s `'message -> unit` callback for consistencies sake doesn't really offer much value(and could lead to confusion), i think `unit -> unit` is fine given the intent, i can't think of anything else that won't be making assumptions.

Documenting **when** this is meant to be used is important. Sending a reliable ack message is a great example(I've run into the same problem), anything that doesn't require the current messages context should be handled via existing means.

**Comment by object** [comment]
Works great in Akkling 0.11.
