### ISSUE TITLE
How to access Eventsourced DeleteMessages and DeleteSnapshots methods?

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#150]
I know this is an advanced feature that is probably deliberately left out of Akkling persistent actor implementation but we have a scenario where we need to clean up old messages and snapshots. Akka.NET C# API (as well as Akka JVM) has the following methods to manage journal events and snapshots that are part of Eventsourced inferface:

- DeleteMessages
- DeleteSnapshot
- DeleteSnapshots
- LoadSnapshot
- SaveSnapshot

None of these methods is available in Akkling. Do you think they can be added to one of Akkling ExtEventsourced interfaces? If you think they don't belong to Akkling, what do you suggest to delete journal message and snapshots?

**Comment by Horusiath** [comment]
Sorry for the late response. I'm thinking about how to fit this API into more declarative frame - JVM version of akka typed serves these features very differently than untyped one.

**Comment by object** [comment]
@Horusiath I reviewed more of Akkling and Akka code regarding this issue. I understand the nextgen F# API to reflect JVM Akka typed is the way to go, but in the meantime it would be great to ensure the current Akkling implementation has access to a full set of Akka features.

One possibility is to enhance PersistentEffect with new messages:

```
and PersistentEffect<'Message> =
    | Persist of 'Message
    | PersistAll of 'Message seq
    | PersistAsync of 'Message
    | PersistAllAsync of 'Message seq
    | Defer of 'Message seq
    | LoadSnapshot of string * SnapshotSelectionCriteria * int64
    | SaveSnapshot of obj
    | DeleteSnapshot of int64
    | DeleteSnapshots of SnapshotSelectionCriteria
    | DeleteMessages of int64
    | AndThen of PersistentEffect<'Message> * (unit -> unit)

```
Then LoadSnapshot implementation will look like this:
```
| LoadSnapshot(persistenceId, criteria, toSequenceNr) -> ctx.LoadSnapshot(persistenceId, criteria, toSequenceNr)
```
This will imply enriching ExtEventsourced with a new interface that will expose new methods or add them to Eventsourced (which is probably is a bad idea because these methods will be rarely used).

One particlar reason I've been investigating this is that I am working on adding at-least-one-delivery semantics to some actors and would like be able to purge all snapshots (and possibly events), something that is not currently available in Akkling.

If you support the idea of extending PersistentEffect with new messages, I can make a pull request.

**Comment by ingted** [comment]
Hi @object , would you mind share the repo address you want to create a PR?

**Comment by Horusiath** [comment]
I've decided to go with @object proposal - it's done in https://github.com/Horusiath/Akkling/commit/9fce6cd8b23dfd201b84b22219c55186e7c841f9
