### ISSUE TITLE
[Question] Why some operators commented out?

### ISSUE THREAD

**Issue by OnurGumus** [Horusiath/Akkling#154]
I have discovered following code is commented out, but commenting in makes them functional
https://github.com/Horusiath/Akkling/blob/62080681cd6e79a51100b38b4c49d0b24634f30e/src/Akkling.Streams/Graph.fs#L96

Any reasons?

**Comment by Horusiath** [comment]
Sorry, but I don't remember the original reason behind this step. Quite possibly it was a result of operator overload clashing, which caused F# compiler type inference to fail, because it couldn't decide which method to use for given operator call.

**Comment by OnurGumus** [comment]
Ok thanks, I have turned it on my code and didn't encounter any problems. Perhaps we need to give it a try, and I know that demands a PR. We'll see.
