### ISSUE TITLE
Migration of Akkling to Akka.NET 1.5

### ISSUE THREAD

**Issue by sbacquet** [Horusiath/Akkling#165]
Akka.NET 1.5 was released recently.
I think some code in Akkling must be amended to comply with Akka.NET 1.5.

Strangely, I met no build issue after moving to Akka.NET 1.5, but only runtime issues, such as : 
```
Message: 
System.MissingMethodException : Method not found: 'System.__Canon Akka.TestKit.TestKitBase.ExpectMsg(System.Predicate`1<System.__Canon>, System.Nullable`1<System.TimeSpan>, System.String)'.

Stack Trace: 
TestKit.expectMsgFilter[t](TestKit tck, FSharpFunc`2 predicate)
```

**Comment by object** [comment]
@sbacquet Did you try the latest Akkling version 0.13? It should fix these issues.

**Comment by sbacquet** [comment]
Indeed, now it's fine. Thank a lot for your fix !
