### ISSUE TITLE
Investigate Vagabond as library for hot code loading

### ISSUE THREAD

**Issue by Horusiath** [Horusiath/Akkling#17]
Right now it's possible to use `spawne` to pass F# quotations over the wire to be hot loaded on another machine. Problem is that if quotation uses functions or types, that are not recognized on another node, the compilation error will occur.

One of the ways to solve that could be [Vagabond](https://github.com/nessos/Vagabond), which is already used for same task on MBrace cloud framework.

PS: _I know that .NET won't allow to unload unused code, even from dynamic assemblies. We need to keep this in mind - this is not even close to what Erlang VM has to offer. However I think, that possible gain is worth the effort_

**Comment by cotyar** [comment]
I think it's a great +1.
Looks like it will require a bit of playing with versioning

**Comment by Horusiath** [comment]
Looking at the history of .NET standard and hot code generation (+ F# integration with it) it looks like it won't be a feasible way in the nearby future. For this reason I also had to remove `propse` and all expression based API in v0.9. Maybe it will land in separate project.
