### ISSUE TITLE
Value restriction for TypedActorSelection.select

### ISSUE THREAD

**Issue by fjoppe** [Horusiath/Akkling#26]
Hi,

I have a remote actor system, and via ActorSelection I want to connect to a specific actor, which is the main entry. I am using the fsi as client. I've followed the [Remote example](https://github.com/Horusiath/Akkling/blob/master/examples/remote.fsx). I am doing it a bit different. I do not deploy a locally made actor to the remote system. I query the remote system using a hard path.

Now this does not work:
```fsharp
let registerPlayer = select actorSystem "akka.tcp://ThisIsMyServer@localhost:8080/user/RegisterPlayer"
```

This results in the following error (in the fsi):
>CallRemoteActor.fsx(38,5): error FS0030: Value restriction. The value 'registerPlayer' has been inferred to have generic type
>    val registerPlayer : TypedActorSelection<'_a>    
>Either define 'registerPlayer' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.

I have studied your code a bit and this does work:
```fsharp
let registerPlayer = TypedActorSelection<RegisterPlayerMessage>(actorSystem.ActorSelection "akka.tcp://ThisIsMyServer@localhost:8080/user/RegisterPlayer")
```

But that's probably not what you wanted..

**Comment by Horusiath** [comment]
I believe, that the problem is the way, F# interactive type inference reacts with structures. This is a quite problematic as I don't want to implement `TypedActorSelection<_>` as class, since this is a simple typed wrapper around `ActorSelection`.

This can be solved by using: 

```fsharp
let registerPlayer = select<ExplicitMessageType> actorSystem "akka.tcp://ThisIsMyServer@localhost:8080/user/RegisterPlayer"
```

**Comment by fjoppe** [comment]
That does not work either:

```fsharp
let registerPlayer = select<RegisterPlayerMessage> actorSystem "akka.tcp://ThisIsMyServer@localhost:8080/user/RegisterPlayer"
```

Results in this message:
>CallRemoteActor.fsx(38,22): warning FS0686: The method or function 'select' should not be given explicit type argument(s) because it does not declare its type parameters explicitly
>
>val registerPlayer : TypedActorSelection<RegisterPlayerMessage> =
>  Akka.Actor.ActorSelection

Which does seem to correspond with the code of the [select function](https://github.com/Horusiath/Akkling/blob/master/src/Akkling/ActorRefs.fs).

Perhaps this is one of those fsharp puzzles. The type at the fsi side will be known at runtime. While this type is known at compile time at the remote site. Theoretically, the remote could even return a type unknown to the fsi; a DU or record only declared locally. But in fsharp, you prefer to use statically typed things. It is probably my lack of knowledge, but this appears as a challenge to me.

Thanks.

**Comment by Horusiath** [comment]
Message from your quote is only a warning, not a FSI error. Your code should work anyway. If I'm right, this can be solved by adding generic signature eplicitly to `select` function definition.

**Comment by fjoppe** [comment]
You are right, it is a warning and it does work indeed. Thanks. 
Now I still got an issue for [Wire](https://github.com/rogeralsing/Wire/issues/16), but that one is probably for Roger.
