### ISSUE TITLE
Could not load type 'Nessos.FsPickler.BinarySerializer'

### ISSUE THREAD

**Issue by ritcoder** [Horusiath/Akkling#39]
I'm getting the above error from the simple code below. What could be wrong?

**Error**

```
An unhandled exception of type 'System.TypeLoadException' occurred in Akkling.dll

Additional information: Could not load type 'Nessos.FsPickler.BinarySerializer' from assembly 'FsPickler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Code**

```
open System
open Akkling
open Akka.Actor

let system = System.create "basic-sys" <| Configuration.defaultConfig() //error here

let behaviour (mailbox:Actor<_>) =
  let rec loop () = actor {
    let! msg = mailbox.Receive ()
    match msg with
    | "stop" -> return Stop
    | "unhandle" -> return Unhandled
    | x ->
        printfn "%s" x
        return! loop ()
  }
  loop ()

let helloRef = spawnAnonymous system (props behaviour)
helloRef <! "ok"
helloRef <! "unhandle"
helloRef <! "ok"

printfn "Press enter to quit"
Console.ReadLine() |> ignore
```

**packages.config**

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Akka" version="1.1.1" targetFramework="net452" />
  <package id="Akka.Serialization.Wire" version="1.1.1.28-beta" targetFramework="net452" />
  <package id="Akkling" version="0.3.0" targetFramework="net452" />
  <package id="FsPickler" version="0.6" targetFramework="net452" />
  <package id="FSPowerPack.Core.Community" version="2.0.0.0" targetFramework="net452" />
  <package id="FSPowerPack.Linq.Community" version="2.0.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net452" />
  <package id="Wire" version="0.0.6" targetFramework="net452" />
</packages>
```

Upgrading `FsPickler`  to `3.1.0.0` resulted in the same error. What am I missing?

**Comment by cotyar** [comment]
FsPickler was moved from Nessos to MBrace namespace (and package AFAIR) with one of the latest library releases. So now it is MBrace.FsPickler.BinarySerializer.

I've got this dependency issue fixed in my pending pull request but unfortunately didn't have a chance yet to apply review comments.

**Comment by cotyar** [comment]
Just rechecked. The nuget package is still the same "FsPickler". So simple swapping to MBrace namespace in open should do the trick.

**Comment by ritcoder** [comment]
Building it from source and adding the dlls to the application worked. Just to be clear, I can't use the nuget package until it is updated, right? Or do I have to point to an older instance of FsPickler?

**Comment by cotyar** [comment]
The highest Akkling nuget available is 0.3.0 which is about 6 month old now.
I would recommend to use paket in your project and set reference to Akkling github in it. At least for now.

**Comment by ritcoder** [comment]
I'm not that familiar with paket. After adding paket to the project, I added the text below to `paket.dependencies`. Didn't know what to add to `paket.references` so it is blank. I added the compiled dlls to the application. The app compiles but is that the correct thing to do?

`git https://github.com/Horusiath/Akkling.git master build: "build.cmd", OS: windows`

**Comment by Horusiath** [comment]
@cotyar Thanks for the info. I'll update the package dependencies and publish next package version this weekend.

**Comment by cotyar** [comment]
@Horusiath Sure, my pleasure. I just pushed in a bit more changes (pls see the pull request). They have all your latest changes and should fix this issue and some other deps problems with latest nugets. (please see my comments on the pull request).

@ritcoder Please feel free to take my fork meanwhile before Bartosz gets a chance to have it reviewed and merged up and release the new nuget for it.

**Comment by Horusiath** [comment]
I think this should be done by now. Feel free to reopen if the issue reappears.
