### ISSUE TITLE
Deliver and exceptions on failure

### ISSUE THREAD

**Issue by Lavinski** [Horusiath/Akkling#47]
In your sample for [at least once delivery](https://github.com/Horusiath/Akkling/blob/master/examples/at-least-once-delivery.fsx) the [Deliver](https://github.com/Horusiath/Akkling/blob/master/examples/at-least-once-delivery.fsx#L65) returns a boolean that is ignored. In functional languages, we usually try and avoid exceptions however with actors and this particular case we probably want the actor to fail and delegate to the supervisor.

The source shows that the exception is just being caught and false returned.

https://github.com/Horusiath/Akkling/blob/fa6474689475af0c327dfbfda1c2b1dbfcc54f40/src/Akkling.Persistence/AtLeastOnceDelivery.fs#L52

I suggest just letting actor functions like those that send, throw exceptions.

**Comment by Horusiath** [comment]
This is explicit choice exactly because we want not to rely on exceptions. We could also return an object with some kind of `IsSuccess` field and `ThrowOnFailure` method to enable both modes.

**Comment by Lavinski** [comment]
That might make it easier to work with (as akka makes heavy use of exceptions). So you'd suggest the result it returns would also have a `ThrowOnFailure` method, which you could use like so.

    deliverer.Deliver(...).ThrowOnFailure()
