### ISSUE TITLE
No Akkling.Streams namespace in the NuGet package

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#52]
0.6.1

![image](https://cloud.githubusercontent.com/assets/873919/25341308/15a3ae52-2911-11e7-9408-5d52ab3ad72a.png)

![image](https://cloud.githubusercontent.com/assets/873919/25341337/2ac6712a-2911-11e7-877b-ec6e9036e0dc.png)

**Comment by Horusiath** [comment]
Akkling.Streams is a [separate NuGet package](https://www.nuget.org/packages/Akkling.Streams/). Please make sure, you're referencing it.

**Comment by vasily-kirichenko** [comment]
It works. Thanks! :)

**Comment by vasily-kirichenko** [comment]
Maybe it's a good idea to add a couple of lines to readme.md about the packages?
