### ISSUE TITLE
How to use Akkling.Streams operators?

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#56]
I see that Akkling Streams graph DSL defines some operators so it should be possible to compose streams in a way similar to Scala graph DSL, however there are no tests or Wiki pages and I simply can't figure out how to use these operators.

Example (without operators):

    let nums = seq { 11..13 }
    let source = nums |> Source.ofSeq
    let sink = Sink.forEach(fun x -> printfn "%d" x)
    let flow = Akka.Streams.Dsl.Flow.FromFunction(fun x -> x * 2)

    source.Via(flow).To(sink) |> Graph.run mat |> ignore

So instead of writing source.Via(flow).To(sink) I should be able to write something like
source ??? flow ??? sink
where ??? stands for some operator from Akkling.Streams.Operators. But none of defined operators seem to match. Can you give some examples of how you meant to use them?

**Comment by Horusiath** [comment]
Unfortunately graph operators are broken right at the moment. I've tried to recreate behavior of scala implementation, but there are several issues:

1. scala uses implicit context (builder) passed as part of operator itself. There's no such thing in F#
2. scala operators can be overloaded into multiple functions targeting different types of stages (and AFAIK there are at least 4-5 different versions of them per each arrow operation). F# custom operators don't have that power.
3. minor case scala default arrow operator `~>` is restricted in F#, where `~` prefix restricts unary prependable operator.

I still need to find a way on how to make those work. For linearizable cases you can use simple forwading, i.e:

```fsharp
Source. ofSeq (seq { 11..13 })
|> Source.map (fun x -> x * 2)
|> Source.runForEach mat (printfn "%d")
```

**Comment by object** [comment]
Thanks for the response. Yes I also banged my head trying to figure out how to achieve something similar to Scala, but didn't come far.

**Comment by Horusiath** [comment]
Closing this one. Graph operators have been introduced in 0.8 and I'll try to work on them more when possible.
