### ISSUE TITLE
Akka IO.Tcp cannot deal with typed actor references

### ISSUE THREAD

**Issue by quartusdev** [Horusiath/Akkling#57]
When running Akkling's Akka Tcp.IO example it doesn't seem to work. I noticed some `System.InvalidCastException`s being thrown "inside" of Akka. Akka seems to attempt to cast `TypedActorRef` to `Akka.Actor.IInternalActorRef`, which fails. 
Replacing lines where actor refs are passed to Akka like 
`IO.Tcp(m) <! TcpMessage.Bind(m.Self, endpoint, 100)` 
with 
`IO.Tcp(m) <! TcpMessage.Bind(untyped m.Self, endpoint, 100)` 
fixes the problems.
But it is obviously not a nice solution, throwing in calls to untyped everywhere. Is there a better solution for fixing this?

**Comment by Horusiath** [comment]
This looks like a bug. I'll take a look at it.

**Comment by quartusdev** [comment]
Thanks. There is the cast: https://github.com/akkadotnet/akka.net/blob/53858e945e41dda307a5ce4ebda328423ba35cef/src/core/Akka/Actor/ActorCell.DeathWatch.cs#L25

**Comment by quartusdev** [comment]
Fixed with #66
