### ISSUE TITLE
Don't inherit Akka.Actor.IActorRef in Akkling.ActorRefs.IActorRef<'Message>?

### ISSUE THREAD

**Issue by quartusdev** [Horusiath/Akkling#63]
I was wondering: Maybe `Akkling.ActorRefs.IActorRef<'Message>` should not inherit `Akka.Actor.IActorRef`. That would probably prevent some incompabilities (like #57 and #59) and at the same time make code more explicit about the boundary between Akka.net's untyped and Akklings's typed actors (forcing to use the `typed`/`untyped` functions).
I know that would be a very hard breaking change, but probably worth it. I would love to hear thoughts on that.

**Comment by quartusdev** [comment]
@Horusiath 
I removed the the inheritance of `IActorRef` and `ICanTell`. Additionally I added another interface `IInternalTypedActorRef`, so that the underlying `IActorRef` can be used in non generic methods like `Equals(obj)` and `CompareTo(obj)`.
See: https://github.com/quartusdev/Akkling/tree/remove-untyped
If you want me to, I can make a PR.

**Comment by Horusiath** [comment]
I think, that PR is a good thing :)

**Comment by j-alexander** [comment]
For a `mailbox:Actor<'T>`, `mailbox.Self` is an `IActorRef<'T>`.  I'm working to update old code that previously used `mailbox.Self.Tell('T, mailbox.Self)` to send a message to itself.

Do you have a recommendation for how to achieve this after the above change?  `Tell` expects the untyped `IActorRef`, and it's now unclear how to obtain that from within the actor itself.

Thanks in advance!  :)

**Comment by Horusiath** [comment]
@j-alexander there's a `untyped` function which unwraps underlying `IActorRef` from its typed version.
