### ISSUE TITLE
How to use stash?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#64]
How to use stash in the following code (taken from `basic.fsx`)?

```fsharp
// 4.2. more implicit
let rec looper state = function
    | "print" -> printfn "Current state: %A" state |> ignored
    | other -> become (looper (other::state))

let stateRef2 = spawnAnonymous system <| props(actorOf (looper []))
```

**Comment by quartusdev** [comment]
You can use [`actorOf2`](https://github.com/Horusiath/Akkling/blob/master/src/Akkling/Spawning.fs#L85) instead of `actorOf`. Then your loop function will receive the actor context and you can call Stash on it.

**Comment by vasily-kirichenko** [comment]
Thanks, it works! :)

**Comment by vasily-kirichenko** [comment]
(I cannot close issue in this repo, unfortunately).
