### ISSUE TITLE
TypeLoadException when using with Akka 1.3.1

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#70]
I tried to update our NuGet packages to use Akka 1.3.1. Then I got bunch of exceptions like this one:

2017-09-06 09:36:22 [Error] "Error while creating actor instance of type Akkling.Actors+FunActor`1[Nrk.Odd.Quartermaster.MonitoringActor+WorkerMessage] with 1 args: 
(Nrk.Odd.Quartermaster.MonitoringActor+spawnMonitoringActor@109)"
[akka://Oddjob/user/monitoring#1836629798]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akkling.Actors+FunActor`1[Nrk.Odd.Quartermaster.MonitoringActor+WorkerMessage] with 1 args: (Nrk.Odd.Quartermaster.MonitoringActor+spawnMonitoringActor@109) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Method 'WatchWith' in type 'TypedContext`2' from assembly 'Akkling, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Akkling.Actors.FunActor`1..ctor(FSharpFunc`2 actor)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)

**Comment by Horusiath** [comment]
The latest minor version introduced new `IActorContext.WatchWith` method. It has not been reflected yet in  F# actor typed context API. I'll publish the updated API soon (hopefully before this weekend).

**Comment by object** [comment]
Great, thanks!

**Comment by object** [comment]
I noticed you pushed a commit with a fix. Now it's just NuGet package that is pending... :-)

**Comment by Horusiath** [comment]
@object unfortunately current master is broken - I'm getting `Couldn't load file or assembly `System.Collections.Immutable, Version=1.2.1.0...` error in xunit tests even thou I've made all steps necessary for correct binding redirects. I think I may need some help here.

**Comment by object** [comment]
Oops. I will clone the master and try to investigate.

**Comment by object** [comment]
Neither Resharper nor VS Test Explorer detect tests. And if I run "build RunTests" or just "build.cmd" (after running paket restore) then the build fails with the error:

Build failed.
Error:
Could not find script 'paket-files/fsharp/FAKE/modules/Octokit/Octokit.fsx' in any paths searched. Searched paths:
["../../../bin"]

How do you usually run tests?

**Comment by Horusiath** [comment]
@object I might have not referenced it, but you need to add Octokit to paket dependencies. I've tried to run it both from R# test runner in VS2017 (15.3) and from build script. Same issue.

**Comment by object** [comment]
I had to install xunit.runner.visualstudio into the test project in order for VS to find the tests:
.paket\paket add nuget xunit.runner.visualstudio -i

Now I am getting the errors about System.Collections.Immutable

**Comment by object** [comment]
I tried to force the version of System.Collections.Immutable by setting it in the paket.dependencies:
nuget System.Collections.Immutable = 1.3.1

This eliminated that error but instead I am getting now from tests Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

This doesn't make sense. There is not even a FSharp.Core NuGet package with such version, the latest version is 4.2.3 (which is set in .lock file).

**Comment by Horusiath** [comment]
@object keep in mind that NuGet version is not the same as assembly version ie. System.Collections.Immutable NuGet v1.3 has assembly version 1.2.1.0, while nuget v1.4 has asm ver 1.2.2.0. 

Also app.config may not work properly due to the latest xunit .net core changes (in v1.X of .net standard have no notion of `ConfigurationManager`). I'm suspecting that this is the reason, why binding redirects don't want to work. AFAIK referencing Microsoft.Tests.SDK should theoretically solve this issue, however I've tried this and I'm still getting the error about System.Collections.Immutable.

Welcome to new .NET standard hell.

**Comment by object** [comment]
I managed to make tests work, and apparently this is the problem with XUnit and AppDomain configuration, see for example here: https://github.com/xunit/xunit/issues/801

So what's happening is that XUnit runner doesn't honor bindingRedirect directives in app.config. To fix it I did the following:

1. Added XUnit appSetting entry to the test project app.config:
  <appSettings>
    <add key="xunit.appDomain" value="required" />
  </appSettings>
2. Added xunit.extensibility.execution NuGet package to package.dependencies.
3. Added xunit.extensibility.execution to Akkling.Tests package.references

Last two changes were supposed to ensure the execution directory contains xunit.execution.desktop.dll that is needed to enable AppDomains for latest XUnit version. But for some reasons the file was still missing, so I copied it manually to the project output folder, and then all tests passed. This is of course a hack that requires a better resolition but at least it's understandable now why tests were failing and what needs to be done to fix them.

**Comment by object** [comment]
But this is hell, fully agree!

**Comment by object** [comment]
Now that the tests are fixed, are you narrowing the Nuget package update?

**Comment by Horusiath** [comment]
I've released v0.7 just a while ago. Waiting for bug issues ;) Closing this one for now.
