### ISSUE TITLE
Overloaded division operator breaks a lot of code

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#71]
Since Akkling Extensions module has AutoOpen attribute, the following operator is redefined:

let inline (/) (x:ActorPath) (y:string) = ActorPath.op_Division(x, y)

And of course it breaks code like this:

let result = 5 / 2
which expects ActorPath operands. So basically Akkling is not compatible with arithmetic operations unless division operator is redefined after importing Akkling.

Since division operator is so widely used, I guess either Extensions module shouldn't have AutoOpen attirbute or another operator should be defined.

**Comment by Horusiath** [comment]
Point taken. I think, it should be probably renamed to something different.

**Comment by vasily-kirichenko** [comment]
I agree. What about `</>`? We use it in our project at work for `Path.Combine` and it looks OK.

**Comment by Horusiath** [comment]
Closing this one. It was fixed some time ago (as a fallback to default `/` operator which is also supported in C#).
