### ISSUE TITLE
Review a Streams example ported

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#76]
In order to learn the Stream wrapper, I've ported https://getakka.net/articles/streams/cookbook.html#balancing-jobs-to-a-fixed-pool-of-workers:
```fsharp
open Akka.Streams
open Akka.Streams.Dsl
open Akkling
open Akkling.Streams
open Akkling.Streams.Operators

let system = System.create "test" (Configuration.defaultConfig())
let mat = system.Materializer()

let balancer worker count =
    Graph.create (fun b ->
        let balancer = b.Add(Balance(count, waitForAllDownstreams = true))
        let merge = b.Add(Merge<_> count)
        for _ in 1..count do
            b.From(balancer) => worker => merge |> ignore
        FlowShape(balancer.In, merge.Out)
    ) |> Flow.FromGraph

let worker = Flow.id |> Flow.map (fun x -> x + 100)

let results = 
    [1..5]
    |> Source.ofList  
    |> Source.via (balancer worker 3)
    |> Source.runForEach mat (printfn "%d") 
    |> Async.RunSynchronously
```
It works, but I have a feeling that it's not very idiomatic (especially the graph definition part).

@Horusiath I believe, you posted a nice graph construction syntax on Twitter. Could you please give a tip how to refactor the code? Thanks.

**Comment by Horusiath** [comment]
I think that the example you've chosen, doesn't look beautiful in any language, even in [Scala](https://doc.akka.io/docs/akka/2.5.5/scala/stream/stream-cookbook.html#balancing-jobs-to-a-fixed-pool-of-workers) ;) 

In most of the cases the noisy part of Graph DSL is builder, which in Scala is implicit param and here it must be used explicitly.

**Comment by vasily-kirichenko** [comment]
Thanks. What do you think about a Graph CE? We could pass the builder implicitly in let! Or I’m wrong?

**Comment by Horusiath** [comment]
This could work! It's a great idea :)
