### ISSUE TITLE
let! inside try...with in actor CE does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#83]
```fsharp
let system = System.create "test" (Configuration.defaultConfig())
let mat = system.Materializer()

let a =
    spawnAnonymous system (props (fun mb ->
        let rec loop() =
            actor {
                let! (_: int) = mb.Receive()
                printfn "calling..."
                try
                    let! _ = async { return 1 }
                    printfn "called!"
                with e ->
                    printfn "error %O!" e
                return! loop()
            }
        loop()))

a <! 0
```
output
```
val a : IActorRef<int> = [akka://test/user/$d#22455368]

a <! 0
calling...
val it : unit = ()

a <! 0
calling...
val it : unit = ()
```
It seems that actor CE has a bug in `Bind` overload for `Async`.

**Comment by Horusiath** [comment]
In general we've found earlier that `try`/`with` construction inside actor expression is broken (no tail call elimination). See: #54 . Unfortunately fixing this will be potentially time-consuming. Right now, this can be omitted by using `actorOf`/`actorOf2` helper methods, which don't use `actor { }` expression.

I think, `actor { }` expression may be dropped in the future in favor of alternative construction (simple function composition, separate to user-defined messages and system-defined signals).

**Comment by vasily-kirichenko** [comment]
I see. But is it possible to call async computation in functions that are passed to `actorOf`/`actorOf2`?

**Comment by Horusiath** [comment]
Not directly at the moment - I probably should add `asyncActorOf` to the API. Until then Akka.NET exposes `void ActorTaskScheduler.Run(Task)` method, which can be used to wrap async computations.

**Comment by vasily-kirichenko** [comment]
`ActorTaskScheduler.Run` accepts `Task` and returns `unit`, but I need to call 
```fsharp
let makeGetRequest<'a> (uri: Uri) : Task<'a> =
        task {
            use client = client()
            let! response = client.GetStringAsync uri
            return FableJson.ofJson<'a> response
        }
```

**Comment by Horusiath** [comment]
Assuming that you're using it inside of your actor:

```fsharp
let handle ctx msg =
    match msg with
    | Request uri ->
        let sender = ctx.Sender ()
        ActorTaskScheduler.RunTask(Func<_>(fun () -> task {
            let! response = makeGetRequest uri
            sender <! response
        })
    ignored()
let aref = spawnAnonymous system <| props (actorOf2 handle)
```

This however will block an actor, preventing it from processing the next message until current one is fully processed (even thou it happens asynchronously).

To make it reentry you can use pipeTo mechanics:

```fsharp
let handle ctx msg =
    match msg with
    | Request uri ->
        makeGetRequest uri
        |> Async.AwaitTask
        |!> ctx.Sender () // this operator is Async equivalent of PipeTo extension method
    ignored()
```
This way actor will trigger a `makeGetRequest` and automatically forward the result to the message sender. Then it will take the next message from the mailbox (it won't wait for this task to complete).

**Comment by vasily-kirichenko** [comment]
I do need to wait for the result (the actor call a service periodically, so it does not make sense to make another call until the previous one finished). So, the first option. But it looks like it blocks a thread pool thread? It's not good, I could do just `let resp = makeGetRequest uri |> Async.RunSynchronously` with the same result :(

**Comment by Horusiath** [comment]
No, it doesn't block in sense of blocking the executing thread. What `ActorTaskScheduler.RunTask` does internally, it suspends actor's mailbox until the task is completed. The Akka message dispatcher, which is responsible for assigning CPU for actor message processing, will ignore those actors which have their mailboxes suspended, giving the processing time only to those, which have opened mailboxes with messages awaiting.

**Comment by vasily-kirichenko** [comment]
Thanks!
