### ISSUE TITLE
Typed request - response?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#87]
There is a "source" actor, other actors send `Get` message to it. In response, it sends `Data` message to `Sender()`. In order to handle this response, the actors have to be untyped (`Actor<obj>`):

```fsharp
module Untyped

open Akkling

type GlobalMsg = Data        
        
module Source =
    type Msg = Get
    
    let props() =
        props (actorOf2 (fun ctx ->
            function 
            | Get -> 
                ctx.Sender() <! Data
                ignored()
        ))      
        
module Actor1 =
    type Msg = Msg
    
    let props (src: IActorRef<Source.Msg>) : Props<obj> =
        props (actorOf (fun (msg: obj) -> 
            match msg with
            | :? Msg ->
                src <! Source.Msg.Get 
                ignored()
            | :? GlobalMsg ->
                // ...
                ignored()
            | _ ->
                unhandled()
        ))        
            
module Actor2 =
    type Msg = Msg
    
    let props (src: IActorRef<Source.Msg>) : Props<obj> =
        props (actorOf (fun (msg: obj) -> 
            match msg with
            | :? Msg ->
                src <! Source.Msg.Get 
                ignored()
            | :? GlobalMsg ->
                // ...
                ignored()
            | _ ->
                unhandled()
        ))        
        
module Test =
    open Akka.Actor

    let sys = ActorSystem.Create "test"
    let src = spawnAnonymous sys (Source.props())
    let a1 = spawnAnonymous sys (Actor1.props src)        
    let a2 = spawnAnonymous sys (Actor2.props src)
```            

Is their a better (more typed) way to design such interaction? I think about `Get of replyTo: IActorRef<xxx>`, but I cannot figure out what `xxx` should be here. In `MailboxProcessor` such a message could be just `Get of AsyncReplyChannel<Data>`, but in Akka.NET we pass actor ref, constrained with a concrete message type, which has nothing to do with the data we want to pass with the response. I hope I just don't understand the right way to use Akka yet :)

**Comment by Horusiath** [comment]
Yes, the preferred way (also promoted in scala by akka-typed) is to have explicit `replyTo: IActorRef<Data>`. I know that in current design you may be limited to recognized current actor as `IActorRef<obj>` in some cases, but then you may use `retype` message which takes `IActorRef<'a>` and returns `IActorRef<'b>`.

In scala there was a `ActorRef[A].narrow[B <: A]: ActorRef[B]` method, which could return a new actor ref of B, where B is subtype of A. However (while it's possible in C#) it's not possible to describe such generic constraint in F#.

**Comment by vasily-kirichenko** [comment]
Aha, `retype`! :) 
```fsharp
type GlobalMsg = Data 
        
module Source =
    type Msg = Get of IActorRef<GlobalMsg>
    
    let props() =
        props (actorOf (function 
            | Get replyTo -> 
                replyTo <! Data
                ignored()
        ))      
        
module Actor1 =
    type Msg = Msg
    
    let props (src: IActorRef<Source.Msg>) : Props<obj> =
        props (actorOf2 (fun (ctx: Actor<obj>) (msg: obj) -> 
            match msg with
            | :? Msg ->
                src <! Source.Msg.Get (retype ctx.Self)
                ignored()
            | :? GlobalMsg ->
                // ...
                ignored()
            | _ ->
                unhandled()
        ))        
```
Looks OK to you?
