### ISSUE TITLE
A better pipeTo

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#88]
Chances are I don't understand the reasoning about sending `Status.Failure` message in case an async/task raises exception, but I find it's not convenient and created this helper:

```fsharp
module Async =
    let pipeTo<'a, 'b> 
        (recipient: ICanTell<'b>)
        (map: Result<'a, exn> -> 'b)
        (computation: Async<'a>): unit =
        
        async {
            let! res = Async.Catch computation
            match res with
            | Choice1Of2 x -> recipient.Tell(map (Ok x), ActorRefs.NoSender)
            | Choice2Of2 e -> recipient.Tell(map (Error e), ActorRefs.NoSender)
        } |> Async.Start
```
usage
```fsharp
type Message = Tick of int | Res of int * Result<unit, exn>

props (actorOf2 (fun ctx (msg: obj) ->
    match msg with
    | :? Message as msg ->
        match msg with
        | Tick n ->
            async {
                if n = 3 then failwithf "it's %d and we are failing" n
                do! Async.Sleep 500
            }
            |> Async.pipeTo ctx.Self (fun x -> box (Res(n, x)))
            
        | Res (n, res) ->
            logInfof ctx "Got %d, %A" n res 
            ctx.Schedule (TimeSpan.FromSeconds 1.0) ctx.Self (box (Tick (n + 1))) |> ignore
        
        ignored()
    
    | LifecycleEvent PreStart ->
        ctx.Self <! box (Tick 0)
        ignored()
        
    | _ -> unhandled()            
)) 
|> spawnAnonymous system
|> ignore
```
What do you think?

**Comment by Horusiath** [comment]
There's already a `pipeTo` method (along with `|!>` and `<!|` operators) - it's not exactly the same, but we could adapt it to this goal.

**Comment by vasily-kirichenko** [comment]
Yes, I saw them. They send 

* the result of the async computation untouched if no exception was thrown
* special `Status.Failure` system message in case of exception

My variant always wrap the result with `Result` and give the user a chance to wrap it further in order to receive a specific message instead of raw `Result`, which has the same issue as `Status.Failure` - we cannot say what concrete async failed. 

Maybe there is a deeper reasoning in sending `Status.Failure` that I don't see?

**Comment by Horusiath** [comment]
I haven't checked if this already has been implemented, but ultimately `Status.Failure` when used inside `Ask<>` will going to be automatically converted to rethrown (with preserving the stacktrace). I'm not sure, if the plan was also, that unhandled `Status.Failure` received by the actor are going to trigger similar behavior.
