### ISSUE TITLE
Using => operator makes graph non generic

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#90]
![image](https://user-images.githubusercontent.com/873919/34919860-65bb5090-f97a-11e7-8bc1-ae4a43284651.png)

![image](https://user-images.githubusercontent.com/873919/34919872-a3e6b4a4-f97a-11e7-837b-25235ddd5667.png)

**Comment by Horusiath** [comment]
Should be fixed now. Feel free to reopen if it will happen again.
