### ISSUE TITLE
No full framework binaries in the NuGet 0.9 package

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#99]
![image](https://user-images.githubusercontent.com/873919/37272761-ba308128-25e8-11e8-8740-c6721da06dc9.png)

which results with no references in projects.

**Comment by pmbanka** [comment]
@Horusiath looks like the fix for Akkling.TestKit was not released, Nuget still shows 0.9 as the latest version https://www.nuget.org/packages/Akkling.TestKit/

**Comment by object** [comment]
Can you please release the NuGet 0.9.1 for Akkling.TestKit? Version 0.9 only supports netstandard, like core Akkling 0.9.

**Comment by Horusiath** [comment]
I'm sorry, I've missed that. I'll try to finish that later today.

**Comment by vasily-kirichenko** [comment]
@Horusiath Everything is OK now. Thanks!

**Comment by object** [comment]
@Horusiath NuGet still reports 0.9 version for Akkling.TestKit (should be 0.9.1)?

**Comment by Horusiath** [comment]
@object for some reason when I'm calling paket create nuget command from FAKE pipeline, all libraries have their nupkg created, except Akkling.TestKit.

**Comment by object** [comment]
Weird. Never seen such behaviour. But perhaps it's possible to create it via nuspec, manually. I know it's tedious work.

**Comment by object** [comment]
Or should I make one and send to you?
